# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'ObjectRow'
  # app.sdk_version = '6.1'
  # app.icons = ["Icon.png", "Icon@2x.png"]
  app.prerendered_icon = true
end
